# Generated by Django 6.0.1 on 2026-01-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
