# Generated by Django 6.0.1 on 2026-01-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.FloatField(default=0),
        ),
    ]
