# Generated by Django 6.0.1 on 2026-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_course_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
